#!/bin/sh

setjdk () {
  if [ $# -ne 0 ]; then
    removeFromPath () {
      export PATH=$(echo $PATH | sed -E -e "s;:$1;;" -e "s;$1:?;;")
    }

    removeFromPath '/System/Library/Frameworks/JavaVM.framework/Home/bin'

    if [ -n "${JAVA_HOME+x}" ]; then
      removeFromPath $JAVA_HOME
    fi

    export JAVA_HOME=`/usr/libexec/java_home -v $@`
    export PATH=$JAVA_HOME/bin:$PATH
  fi

  echo JAVA_HOME set to $JAVA_HOME
  java -version
}